#!/usr/bin/env ruby

require 'burglar'

def local_cmd
  `ledger --no-pager --empty --flat --no-total -C balance Assets Liabilities`
end

def get_local
  raw = local_cmd.split("\n").map do |x|
    x.split.values_at(1, 0)
  end
  raw.to_h.transform_values { |x| x.gsub(/[,$]/, '').to_f.abs }
end

upstream = Burglar.new.banks.map { |_, v| [v.account_name, v.balance] }
local = get_local

fails = 0

upstream.each do |k, v|
  a = local[k]
  puts("bad account: #{k}") unless a
  next if v == a
  puts "Mismatch found for #{k} -- upstream #{v} / local #{a} / delta #{v - a}"
  fails += 1
end

if fails == 0
  puts 'Balances aligned'
  exit 0
end

exit 1
